let env = window.location.hostname
  .substring(0, window.location.hostname.indexOf("."))
  .toUpperCase();

env = env || "QA"; //in case of localhost

let relativePaths = {
  APP: {
    production: false,
    APIbaseUrlDirect: "https://analytics.sibme.com",
    APIbaseUrl: "https://api.sibme.com",
    baseHeaderUrl: "https://app.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://app.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://app.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  },
  QA: {
    production: false,
    APIbaseUrl: "https://qaapi.sibme.com",
    baseHeaderUrl: "https://qa.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://qa.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://qa.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  },
  Q2: {
    production: false,
    // APIbaseUrlDirect: "https://analytics.sibme.com",
    APIbaseUrl: "https://q2api.sibme.com",
    baseHeaderUrl: "https://q2.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://q2.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://q2.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: true,
    project_title:'huddle_list',
    channelsArr: []
  },
  Q21: {
    production: false,
    APIbaseUrl: "https://q21api.sibme.com",
    baseHeaderUrl: "https://q21.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://q21.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://q21.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: true,
    project_title:'huddle_list',
    channelsArr: []
  },
  Q22: {
    production: false,
    APIbaseUrl: "https://q22api.sibme.com",
    baseHeaderUrl: "https://q22.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://q22.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://q22.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: true,
    project_title:'huddle_list',
    channelsArr: []
  },
  Q3: {
    production: false,
    APIbaseUrl: "https://q3api.sibme.com",
    baseHeaderUrl: "https://q3.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://q3.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://q3.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: true,
    project_title:'huddle_list',
    channelsArr: []
  },
  STAGING: {
    production: false,
    APIbaseUrl: "https://stagingapi.sibme.com",
    baseHeaderUrl: "https://staging.sibme.com/api",
    deploymentPath: "app/webroot/video_details",
    baseUrl: "https://staging.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://staging.sibme.com",
    appUrl: "http://sibme.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  },
  HMH: {
    production: false,
    APIbaseUrl: "https://hmhapi.sibme.com",
    // APIbaseUrlDirect: "https://analyticscs.sibme.com",
    baseHeaderUrl: "https://hmh.sibme.com/api",
    deploymentPath: "app/webroot/add_huddle_angular",
    baseUrl: "https://hmh.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://hmh.sibme.com",
    appUrl: "http://hmh.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  },
  Q2HMH: {
      production: false,
      // APIbaseUrlDirect: "https://analyticscs.sibme.com",
      APIbaseUrl: "https://q2hmhapi.sibme.com",
      baseHeaderUrl: "https://q2hmh.sibme.com/api",
      deploymentPath: "app/webroot/add_huddle_angular",
      baseUrl: "https://q2hmh.sibme.com",
      fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
      container: "sibme-production",
      appPath: "https://q2hmh.sibme.com",
      appUrl: "http://hmh.com",
      imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
      enableLogging: false,
      project_title:'huddle_list',
      channelsArr: []
  },
  QAHMH: {
    production: false,
    APIbaseUrl: "https://qahmhapi.sibme.com",
    baseHeaderUrl: "https://qahmh.sibme.com/api",
    deploymentPath: "app/webroot/add_huddle_angular",
    baseUrl: "https://qahmh.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://qahmh.sibme.com",
    appUrl: "http://hmh.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
},
WL: {
    production: false,
    // APIbaseUrlDirect: "https://analytics.sibme.com",
    APIbaseUrl: "https://wlapi.sibme.com",
    baseHeaderUrl: "https://wl.sibme.com/api",
    deploymentPath: "app/webroot/add_huddle_angular",
    baseUrl: "https://wl.sibme.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://wl.sibme.com",
    appUrl: "http://hmh.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  },
  COACHINGSTUDIO: {
    production: true,
    APIbaseUrlDirect: "https://analyticscs.sibme.com",
    APIbaseUrl: "https://csapi.sibme.com",
    baseHeaderUrl: "https://coachingstudio.hmhco.com/api",
    deploymentPath: "app/webroot/add_huddle_angular",
    baseUrl: "https://coachingstudio.hmhco.com",
    fileStackAPIKey: "A3w6JbXR2RJmKr3kfnbZtz",
    container: "sibme-production",
    appPath: "https://coachingstudio.hmhco.com",
    appUrl: "https://coachingstudio.hmhco.com",
    imageBaseUrl: "https://s3.amazonaws.com/sibme.com/static/users",
    enableLogging: false,
    project_title:'huddle_list',
    channelsArr: []
  }
};

export const environment = relativePaths[env];
